# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ra-Mo
tagline:          'iOS Development'
description:      'A blog about iOS Dev, Software Craftsmanship, and Agile practices'
url:              http://raphaelmor.github.io

author:
  name:           'RaphaÃ«l Mor'
  url:            https://twitter.com/raphaelmor

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/raphaelmor
